# Generated by Django 6.0 on 2026-04-30 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_profile_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
